name: ran_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: any
  notification_permissions: ^0.6.1
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.1
  shared_preferences: ^2.2.3
  flutter_cupertino_datetime_picker: ^3.0.0
  time_planner: ^0.1.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^2.3.3+1
  flutter_native_splash: ^2.2.18
  flutter_lints: ^3.0.0
  time_range: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/diddy.jpeg

flutter_native_splash:
  color: "#FFFFFF"  # Replace this with the background color you want
  image: assets/images/diddy.jpeg  # Path to your splash screen image
  android: true  # Enable Android splash screen
  ios: true  # Enable iOS splash screen
  fullscreen: true  # Makes the splash screen full screen

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/diddy.jpeg"
